name: Unsupervised-Clustering
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - asttokens==2.4.0
      - backcall==0.2.0
      - contourpy==1.1.1
      - cycler==0.11.0
      - cython==0.29.36
      - decorator==5.1.1
      - executing==1.2.0
      - fonttools==4.42.1
      - hdbscan==0.8.33
      - ipython==8.15.0
      - jedi==0.19.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - llvmlite==0.41.0
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mizani==0.9.3
      - numba==0.58.0
      - numpy==1.25.2
      - packaging==23.1
      - pandas==2.1.1
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - plotnine==0.12.3
      - polars==0.19.3
      - prompt-toolkit==3.0.39
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pygments==2.16.1
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - seaborn==0.12.2
      - six==1.16.0
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - tbb==2021.10.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - traitlets==5.10.1
      - tzdata==2023.3
      - umap-learn==0.5.4
      - wcwidth==0.2.6
